// // // This file was generated by Prisma, and assumes you have installed the following:
// // // npm install --save-dev prisma dotenv
// import 'dotenv/config'
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//     seed: 'tsx prisma/seed.ts',
//   },
//   datasource: {
//     url: env('DATABASE_URL'),
//   },
// });

// prisma.config.ts
import dotenv from "dotenv";
dotenv.config({ path: "prisma/.env" });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations", seed: "tsx prisma/seed.ts" },
  datasource: { url: "postgres://app:app@db:5432/app" },
});